name: "Comprehensive API Test - JSONPlaceholder"
description: "Tests multiple endpoints, field mappings, data path, all rule types for an API job, outputting to JSON."
job_type: api

api_config:
  base_url: "https://jsonplaceholder.typicode.com"
  endpoints:
    - "/users"
    - "/posts/1"
  method: "GET"
  data_path: "" # For /users, root is list. For /posts/1, root is object.
  field_mappings:
    user_id: "id"
    full_name: "name"
    username: "username"
    email_address: "email"
    city: "address.city"
    company_bs_original: "company.bs" # Keep original for transformation
    post_id_single: "id"
    post_title_single: "title"

output_format: json

processing_rules:
  field_types:
    user_id: {type: "int"}
    post_id_single: {type: "int"}
  text_cleaning:
    full_name:
      trim: true
      uppercase: true
    username:
      lowercase: true
    post_title_single:
      trim: true
  validations:
    email_address: {required: true, pattern: "^[\\w\\.-]+@[\\w\\.-]+\\.\\w+$"}
    username: {min_length: 3}
    post_title_single: {required: true}
  transformations:
    name_and_email: "f\"{item.get('full_name', '')} <{item.get('email_address', '')}>\" if item.get('full_name') and item.get('email_address') else None"
    company_bs_transformed: "item.get('company_bs_original', '').replace(' ', '_') if item.get('company_bs_original') else None"
    data_source: "'post_detail' if 'post_id_single' in item else ('user_list' if 'user_id' in item else 'unknown')"
  drop_fields:
    - "company_bs_original" # Drop the original after transforming

request_delay: 0.2
max_retries: 3
user_agent: "MyComprehensiveAPITester/1.1"
