name: "API Test - JSONPlaceholder Users"
description: "Fetch user data from JSONPlaceholder API"
job_type: api

api_config:
  base_url: "https://jsonplaceholder.typicode.com"
  endpoints:
    - "/users"
  # Optional fields below:
  method: "GET"
  # params: {"_limit": 5}
  # headers: {"Accept": "application/json"}
  data_path: "" # Optional: Path to items (empty means root is the list)
  field_mappings: # Optional: Rename fields
    user_id: "id"
    full_name": "name"
    email: "email"
    city: "address.city"
    company_name: "company.name"

processing_rules:
    text_cleaning:
      full_name: {trim: True}
    validations:
      email: {required: true, pattern: "^.+@.+\\..+$"}

output_dir: "outputs/api_test"
# proxies: [] # Add if testing API through proxies
