name: "Amazon Product Scraper"
description: "Scrape product prices from Amazon search results"
urls:
  - "https://www.amazon.com/s?k=laptops"
dynamic: true
selectors:
  type: css
  container: "div.s-main-slot"
  item: "div[data-component-type='s-search-result']"
  fields:
    title: "h2 a span.a-text-normal"
    price_symbol: "span.a-price-symbol"
    price_whole: "span.a-price-whole"
    price_fraction: "span.a-price-fraction"
    rating: "span.a-icon-alt"
    url: {"selector": "h2 a.a-link-normal", "attr": "href"}
    image_url: {"selector": "img.s-image", "attr": "src"}

processing_rules:
  field_types:
    rating_value: {"type": "float"}
  text_cleaning:
    title: {"trim": True}
    rating: {"trim": True}
  validations:
    url: {"required": True, "pattern": r"^/dp/"}
    price_whole: {"required": True}
  transformations:
    price: |
      (
          float(item.get('price_whole', '0').replace(',', '')) +
          float(item.get('price_fraction', '0')) / 100
      ) if item.get('price_whole') else None
    rating_value: |
      float(value.split()[0]) if isinstance(value, str) and 'out of' in value else None
    full_url: "'https://www.amazon.com' + value if isinstance(value, str) and value.startswith('/dp/') else value"
  # --- Corrected Key ---
  drop_fields: ["price_symbol", "price_whole", "price_fraction", "rating"]
  # --- End Correction ---

pagination:
  next_page_selector: "a.s-pagination-item.s-pagination-next"
  max_pages: 3

output_dir: "outputs/amazon_laptops"
request_delay: 4
max_retries: 2
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36"
respect_robots: True
wait_for_selector: "div[data-component-type='s-search-result']"
headless: True
page_load_timeout: 45
