proxies:
  - http: 'http://127.0.0.1:1' # Invalid port
    https: 'http://127.0.0.1:1'

name: Quotes Scraper Test - Paged
description: Test scraping multiple pages of quotes.toscrape.com
urls: # <- Ensure 'urls' key is correct
  - https://quotes.toscrape.com/ # Start URL
dynamic: false
selectors: # <- Ensure 'selectors' key is correct
  # container: div.row div.col-md-8 # Ignored by current scraper
  item: div.quote
  fields:
    quote_text: span.text
    author: small.author
    tags_raw: div.tags

# --- Added/Ensure Pagination Rules ---
pagination: # <- Ensure 'pagination' key is correct
  next_page_selector: li.next a # Selector for the 'Next →' link <a> tag
  max_pages: 3 # Limit to scraping 3 pages total for testing

# --- Keep Processing Rules ---
processing_rules: # <- Ensure 'processing_rules' key is correct
  text_cleaning:
    quote_text: {trim: true, regex_replace: {'^[“”"]': '', '[“”"]$': ''}}
    author: {trim: true}
  validations:
    quote_text: {required: true, min_length: 5}
    author: {required: true}
  transformations:
    # Use YAML literal block style for better readability of the expression
    tags: |
      ', '.join(tag.strip() for tag in value.replace('Tags:', '').split('\n') if tag.strip()) if isinstance(value, str) else ''
  drop_fields:
    - tags_raw

output_dir: outputs/quotes_paged # Use a specific output dir
request_delay: 1
max_retries: 2
user_agent: Mozilla/5.0 (compatible; MyTestScraper/1.1)
respect_robots: true
