name: Quotes Scraper Test - XPath
description: Test scraping quotes.toscrape.com using XPath selectors.
urls:
  - https://quotes.toscrape.com/ # Start URL
dynamic: false # Use HTMLScraper

selectors:
  type: xpath # <--- Set type to xpath
  item: "//div[@class='quote']" # XPath for each quote div
  fields:
    # Use XPath functions/paths relative to the item context (.)
    quote_text: ".//span[@class='text']/text()" # Gets the direct text of the span
    author: ".//small[@class='author']/text()"  # Gets the direct text of the small tag
    # Example of getting an attribute value directly with XPath
    tags: ".//div[@class='tags']/meta[@itemprop='keywords']/@content"

pagination:
  next_page_selector: "li.next a" # CSS selector used by base scraper for finding next page URL
  max_pages: 2

processing_rules:
  # Example: Clean quotes by removing leading/trailing quote marks if needed
  # text_cleaning:
  #   quote_text: {regex_replace: {'^“|”$': ''}}
  validations:
    quote_text: {required: true}
    author: {required: true} # Corrected key

output_dir: "outputs/quotes_xpath_test"
request_delay": 1
max_retries": 3
user_agent: "Mozilla/5.0 (compatible; MyTestScraper/1.2; +http://mytest.com/bot)"
respect_robots: true
proxies: [] # No proxies for this test
